"""Generate 2000 more AI samples to reach 5000 total (files 3001-5000)."""
import os, random

output_dir = r"c:\voice-check\dataset_text\ai"
start_idx = 3001
target = 5000

topics = [
    # Science
    "Mitosis is the process of cell division that results in two genetically identical daughter cells. It is divided into four phases: prophase, metaphase, anaphase, and telophase. During prophase, chromosomes condense and become visible. In metaphase, chromosomes align at the cell's equator. Anaphase sees sister chromatids pulled to opposite poles, and in telophase, two new nuclei form. Mitosis is essential for growth, repair, and asexual reproduction.",
    "Acids and bases are fundamental chemical concepts. Acids donate protons and have a pH below 7, while bases accept protons and have a pH above 7. The pH scale ranges from 0 to 14, with 7 being neutral. Strong acids like hydrochloric acid fully dissociate in water, whereas weak acids like acetic acid partially dissociate. Neutralization reactions between acids and bases produce water and salt, and are widely used in industrial and biological processes.",
    "The law of conservation of mass states that matter cannot be created or destroyed in a chemical reaction. The total mass of reactants always equals the total mass of products. This principle is reflected in balanced chemical equations, where the number of atoms of each element is the same on both sides. Antoine Lavoisier established this fundamental law through careful experimentation in the 18th century.",
    "Light travels at approximately 300,000 kilometers per second in a vacuum. When light passes from one medium to another, it changes speed and bends — a phenomenon called refraction. The degree of bending depends on the refractive indices of the two media. This principle is used in the design of lenses, prisms, and optical fibers. Total internal reflection, where light is completely reflected within a medium, is the basis for fiber optic communication technology.",
    "The endocrine system regulates bodily functions through hormones secreted by glands directly into the bloodstream. Key glands include the pituitary, thyroid, adrenal glands, and pancreas. The pituitary gland, often called the master gland, controls other endocrine glands. Insulin, produced by the pancreas, regulates blood glucose levels. Hormonal imbalances can lead to disorders such as diabetes, thyroid disease, and growth abnormalities.",
    "Waves are disturbances that transfer energy through matter or space. They are characterized by amplitude, wavelength, frequency, and speed. Transverse waves, like light and water waves, oscillate perpendicular to the direction of travel. Longitudinal waves, like sound waves, oscillate parallel to the direction of travel. The Doppler effect describes the change in perceived frequency when a wave source and observer move relative to each other.",
    "Ecology is the study of the interactions between living organisms and their environment. A food web describes the complex feeding relationships within an ecosystem. Primary producers form the base, converting solar energy into organic matter. Primary consumers eat producers, secondary consumers eat primary consumers, and so on. Energy is lost at each trophic level, which is why ecosystems can support fewer apex predators than primary consumers.",
    "The human nervous system consists of the central nervous system (brain and spinal cord) and the peripheral nervous system. Neurons are the basic functional units that transmit electrical and chemical signals. A typical neuron has dendrites that receive signals, a cell body, and an axon that transmits signals to other neurons. Synapses are junctions where neurons communicate through neurotransmitters such as dopamine, serotonin, and acetylcholine.",
    "Genetic inheritance follows principles first described by Gregor Mendel. Dominant alleles mask the expression of recessive alleles when both are present. An organism's genotype refers to its genetic makeup, while the phenotype is the observable expression of those genes. Punnett squares are used to predict the probability of offspring inheriting specific traits. Modern genetics has expanded Mendel's work to include incomplete dominance, codominance, and polygenic traits.",
    "Chemical equilibrium occurs in reversible reactions when the rate of the forward reaction equals the rate of the reverse reaction. At equilibrium, the concentrations of reactants and products remain constant. Le Chatelier's Principle states that if a system at equilibrium is disturbed, it will shift to counteract the disturbance and restore equilibrium. This principle is applied in industrial chemistry to maximize product yield.",
    # Technology
    "Cloud computing delivers computing resources — including servers, storage, databases, and software — over the internet on a pay-per-use basis. The three primary service models are Infrastructure as a Service (IaaS), Platform as a Service (PaaS), and Software as a Service (SaaS). Cloud computing enables organizations to scale resources quickly without large upfront capital investments. Major providers include Amazon Web Services, Microsoft Azure, and Google Cloud Platform.",
    "The Internet of Things connects everyday physical devices to the internet, enabling them to collect and share data. Smart home devices, industrial sensors, wearable health monitors, and connected vehicles are all part of this ecosystem. IoT generates massive amounts of data that can be analyzed to optimize efficiency and enable new services. Security and privacy are major concerns, as each connected device represents a potential vulnerability in a network.",
    "Cybersecurity threats have evolved significantly as digital infrastructure has become more complex and interconnected. Ransomware attacks encrypt victims' data and demand payment for decryption keys. Phishing campaigns trick users into revealing credentials through deceptive emails or websites. Zero-day exploits take advantage of previously unknown software vulnerabilities. Effective defense requires a layered approach combining technical controls, user education, and rapid incident response capabilities.",
    "5G wireless technology represents a major advancement over previous generations, offering significantly higher data speeds, lower latency, and the ability to connect many more devices simultaneously. It operates on a range of frequency bands, with millimeter wave frequencies providing the highest speeds but shorter range. 5G is expected to enable new applications including autonomous vehicles, remote surgery, and smart city infrastructure that require real-time, reliable connectivity.",
    "Natural language processing (NLP) is a branch of artificial intelligence that enables computers to understand, interpret, and generate human language. Modern NLP systems use transformer-based neural network architectures trained on vast text corpora. Applications include machine translation, sentiment analysis, chatbots, and text summarization. Large language models have demonstrated remarkable capabilities in generating coherent, contextually appropriate text across a wide range of domains.",
    # Social Studies
    "The Cold War was a period of geopolitical tension between the United States and the Soviet Union and their respective allies from approximately 1947 to 1991. Rather than direct military confrontation, it was characterized by proxy wars, an arms race, the space race, and ideological competition between capitalism and communism. Key events included the Berlin Blockade, the Cuban Missile Crisis, and the Korean and Vietnam Wars. The dissolution of the Soviet Union in 1991 marked its end.",
    "Colonialism profoundly shaped the modern world by enabling European powers to extract resources from and exert political control over vast territories in Africa, Asia, and the Americas from the 15th century onward. Colonial rule suppressed indigenous cultures, languages, and political structures while creating extractive economic systems that benefited colonizers. The legacy of colonialism continues to influence global inequalities, political instability, and cultural dynamics in formerly colonized regions.",
    "The Silk Road was an ancient network of trade routes that connected China, Central Asia, South Asia, the Middle East, and Europe. Beyond goods like silk, spices, and precious metals, these routes facilitated the exchange of ideas, religions, technologies, and diseases. Buddhism, Islam, and Christianity all spread along these routes. The Silk Road fostered cultural interactions that shaped civilizations across Eurasia for over a millennium.",
    "Federalism divides governmental authority between a central national government and regional state or provincial governments. Each level of government has defined powers and responsibilities. The United States Constitution establishes this division, granting specific powers to the federal government while reserving others to states. Federalism allows for policy experimentation at the state level and accommodates regional diversity, but can also create tensions over jurisdictional boundaries.",
    "The Green Revolution of the mid-20th century dramatically increased agricultural production through the development of high-yielding crop varieties, expanded use of irrigation, chemical fertilizers, and pesticides. Led by Norman Borlaug and others, it is credited with averting widespread famine in developing countries and feeding a rapidly growing global population. However, it also contributed to environmental problems including soil degradation, water pollution, and biodiversity loss.",
    # Health & Environment
    "Antibiotic resistance is one of the most serious global public health threats. When bacteria are exposed to antibiotics, susceptible bacteria die while resistant ones survive and reproduce. The overuse and misuse of antibiotics in medicine and agriculture has accelerated this process. Resistant infections are more difficult and expensive to treat, and some pathogens are becoming resistant to all available antibiotics. Addressing this crisis requires strict prescribing practices, reduced agricultural antibiotic use, and investment in new drug development.",
    "The ozone layer in the stratosphere absorbs most of the sun's harmful ultraviolet radiation, protecting life on Earth. In the 1970s, scientists discovered that chlorofluorocarbons (CFCs) and other industrial chemicals were destroying ozone molecules. The Montreal Protocol, signed in 1987, successfully phased out the production of ozone-depleting substances. The ozone layer is slowly recovering, demonstrating that international environmental cooperation can effectively address global environmental problems.",
    "Soil is a complex mixture of minerals, organic matter, water, air, and microorganisms that supports plant growth and ecosystem function. It takes hundreds to thousands of years to form just a few centimeters of topsoil through the weathering of rock and decomposition of organic matter. Unsustainable agricultural practices, deforestation, and urbanization are causing soil degradation worldwide, threatening food security and ecosystem services.",
    "Sleep is essential for physical and mental health. During sleep, the brain consolidates memories, removes metabolic waste, and regulates emotions. Adults typically need seven to nine hours of sleep per night. Chronic sleep deprivation is associated with increased risk of obesity, diabetes, cardiovascular disease, and mental health disorders. Modern lifestyles, including screen use before bedtime and irregular schedules, increasingly disrupt natural sleep patterns.",
    "Malnutrition encompasses both undernutrition and overnutrition and affects people in all countries. Undernutrition, including stunting and wasting in children, results from inadequate intake of calories and essential nutrients. Overnutrition, leading to overweight and obesity, results from excessive caloric intake and poor diet quality. Both forms impair health and cognitive development. Addressing malnutrition requires improving food systems, nutrition education, and access to diverse, nutrient-rich foods.",
    # Economics & Politics
    "Inflation is the rate at which the general level of prices for goods and services rises, reducing purchasing power. Central banks aim to maintain a stable, low rate of inflation. Demand-pull inflation occurs when aggregate demand exceeds supply, while cost-push inflation results from rising production costs. Hyperinflation, where prices rise extremely rapidly, can devastate economies. Central banks use interest rate adjustments and other monetary policy tools to manage inflation.",
    "Public goods are goods that are non-excludable, meaning no one can be prevented from using them, and non-rivalrous, meaning one person's use does not diminish availability to others. National defense, public parks, and clean air are examples. Because private markets tend to underprovide public goods due to the free-rider problem, governments typically take responsibility for their provision. The challenge of financing and allocating public goods is a central concern of public economics.",
    "The welfare state refers to a system in which the government plays a key role in protecting the economic and social well-being of its citizens. Components typically include universal healthcare, public education, unemployment insurance, and pension systems. Scandinavian countries have developed extensive welfare states with high levels of social protection. Critics argue that generous welfare systems reduce work incentives and create unsustainable fiscal burdens, while supporters point to their role in reducing poverty and inequality.",
    "International trade allows countries to specialize in producing goods and services in which they have a comparative advantage and exchange them for goods others produce more efficiently. Trade agreements reduce tariffs and other barriers to facilitate this exchange. Free trade is generally supported by economists as increasing overall economic output, but it also creates winners and losers, with some industries and workers facing intense competition from imports. Managing trade's distributional effects is a key policy challenge.",
    "Urbanization is accelerating in developing countries, with millions of people moving to cities annually in search of economic opportunities. While cities drive economic growth and innovation, rapid urbanization often outpaces the development of infrastructure, housing, and services. Informal settlements, or slums, house large portions of urban populations in many developing countries. Sustainable urban development requires inclusive planning, investment in affordable housing, and the expansion of public transportation and basic services.",
]

generated = 0
for idx in range(start_idx, target + 1):
    text = random.choice(topics)
    out_path = os.path.join(output_dir, f"{idx}.txt")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(text)
    generated += 1
    if generated % 500 == 0:
        print(f"  Generated {generated} files (up to index {idx})...")

print(f"\nDone! Generated {generated} new AI samples (files {start_idx}-{target}).")
print(f"Total AI samples now: {target}")
