"""Generate 111 more AI samples to reach 3000 total (files 2890-3000)."""
import os, random

output_dir = r"c:\voice-check\dataset_text\ai"
start_idx = 2890
target = 3000

topics = [
    "Machine learning algorithms are designed to improve their performance through experience and data. Supervised learning involves training a model on labeled examples, while unsupervised learning discovers hidden patterns in unlabeled data. Reinforcement learning trains agents through reward signals. These approaches power modern applications including recommendation engines, fraud detection systems, and autonomous vehicles.",
    "The water cycle, also known as the hydrological cycle, describes the continuous movement of water through Earth's systems. Water evaporates from oceans and lakes, rises as water vapor, condenses into clouds, and falls as precipitation. This cycle is essential for distributing freshwater across the planet and regulating climate. Human activities such as deforestation and urbanization significantly alter natural water flow patterns.",
    "Supply and demand are the fundamental forces that determine prices in a market economy. When demand for a product increases while supply remains constant, prices rise. Conversely, when supply exceeds demand, prices fall. Understanding these dynamics is essential for businesses making production decisions and for policymakers designing effective economic interventions.",
    "The periodic table organizes all known chemical elements by their atomic number and electron configuration. Elements in the same group share similar chemical properties because they have the same number of valence electrons. The table's structure allows scientists to predict how elements will react and what properties new elements might have. Modern versions contain 118 confirmed elements, ranging from hydrogen to oganesson.",
    "Photosynthesis is the process by which green plants, algae, and some bacteria convert light energy into chemical energy stored in glucose. The reaction requires carbon dioxide, water, and sunlight, releasing oxygen as a byproduct. Chlorophyll in plant cells absorbs primarily red and blue wavelengths of light. This process is the foundation of virtually all food chains on Earth.",
    "The human immune system is a complex network of cells, tissues, and organs that work together to defend the body against pathogens. Innate immunity provides immediate, non-specific defense through physical barriers and inflammatory responses. Adaptive immunity develops targeted responses through B and T lymphocytes that recognize specific antigens. Memory cells ensure a faster, stronger response upon subsequent exposure to the same pathogen.",
    "Democratic governance relies on the principles of political equality, rule of law, and protection of individual rights. Free and fair elections allow citizens to choose their representatives and hold them accountable. Independent judiciaries protect constitutional rights and resolve disputes. A free press and civil society organizations serve as watchdogs, ensuring transparency and challenging abuses of power.",
    "The theory of evolution by natural selection, proposed by Charles Darwin, explains how species change over time. Individuals with traits better suited to their environment are more likely to survive and reproduce, passing those advantageous traits to offspring. Over many generations, this process results in the gradual transformation of species. The fossil record, comparative anatomy, and genetic evidence all strongly support evolutionary theory.",
    "Electrical energy can be generated from various sources including fossil fuels, nuclear fission, and renewable resources. In thermal power plants, heat converts water into steam that drives turbines connected to generators. Solar panels convert sunlight directly into electricity through the photovoltaic effect. Wind turbines capture kinetic energy from moving air. The transition to renewable energy sources is critical for reducing greenhouse gas emissions.",
    "Economic globalization has increased the interdependence of national economies through trade, investment, and the movement of people. Multinational corporations operate across borders, benefiting from lower production costs and accessing larger markets. While globalization has contributed to economic growth and poverty reduction in many regions, it has also created challenges including job displacement, income inequality, and the spread of financial crises across interconnected markets.",
    "The cardiovascular system consists of the heart, blood vessels, and blood, working together to transport oxygen, nutrients, and hormones throughout the body. The heart pumps blood through two circuits: the pulmonary circuit, which carries blood to the lungs for oxygenation, and the systemic circuit, which delivers oxygenated blood to body tissues. Regular exercise, a balanced diet, and avoiding smoking are key to maintaining cardiovascular health.",
    "Artificial neural networks are computational models inspired by the structure and function of the human brain. They consist of interconnected layers of nodes that process information through weighted connections. During training, the network adjusts these weights using backpropagation to minimize prediction errors. Deep neural networks with many layers can learn highly complex patterns and have achieved remarkable performance in tasks such as image recognition and language translation.",
    "Climate change is causing significant shifts in global weather patterns, sea levels, and biodiversity. Rising temperatures are melting polar ice caps and glaciers, contributing to sea level rise that threatens coastal communities. Changes in precipitation patterns are increasing the frequency and severity of droughts and floods. International agreements such as the Paris Agreement aim to limit global warming by reducing greenhouse gas emissions through coordinated national action.",
    "The principles of thermodynamics govern the behavior of energy in physical systems. The first law states that energy cannot be created or destroyed, only converted from one form to another. The second law introduces the concept of entropy, stating that disorder in an isolated system always increases over time. These principles have profound implications for engineering, chemistry, and our understanding of the ultimate fate of the universe.",
    "Biodiversity refers to the variety of life forms on Earth, from microorganisms to complex multicellular organisms. High biodiversity is associated with ecosystem resilience, as diverse communities can better withstand disturbances. Biodiversity provides essential ecosystem services including pollination, water purification, and climate regulation. The current rate of species extinction is estimated to be one thousand times higher than the natural background rate, primarily due to human activities.",
]

generated = 0
for idx in range(start_idx, target + 1):
    text = random.choice(topics)
    out_path = os.path.join(output_dir, f"{idx}.txt")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(text)
    generated += 1

print(f"Done! Generated {generated} new AI samples (files {start_idx}-{target}).")
print(f"Total AI samples now: {target}")
